spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WaterMeter
    username: postgres
    password: 1234
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9095